language: python
services:
    - potgresql
python:
    - "3.4"
    - "3.5"
install: "pip3 install -r requirements.txt"
before_script:
    - cp core/local_settings.py.example core/local_settings.py
    - psql -c 'create database dgap_voting_db_test;' -U postgres
    - python manage.py makemigrations
    - python manage.py migrate
script:
    - python manage.py test
